site_name: ot1j9dc4rdqcs45pcvpho3jgr

docs_dir: ot1j9dc4rdqcs45pcvpho3jgr

theme:
  name: material
  features:
    - navigation.indexes
  palette:
    # Automatic/System Mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

plugins:
  - search

validation:
  nav:
    not_found: info
    omitted_files: info
  links:
    not_found: info

nav:
  - Home: index.md

  - Glossary: glossary.md

  - User Guide:
      - user_guide/index.md
      - Pixi (preferred): user_guide/pixi_usage.md
      - Uv: user_guide/uv_usage.md
      - Pip: user_guide/pip_usage.md

  - Help and Support:
      - help_and_support/index.md
      - Ticketing: help_and_support/ticketing.md
      - Labels: help_and_support/labels.md

  - Development and Community:
      - development_and_community/index.md
      - Contributing: development_and_community/contributing.md
      - Maintaining: development_and_community/maintaining.md
      - Contributors: development_and_community/contributors.md

  - About Repository:
      - about_repository/index.md
      - Labels: about_repository/labels.md

  - Governance and Legal:
      - governance_and_legal/index.md
      - Governance: governance_and_legal/governance.md
      - Code of Conduct: governance_and_legal/code_of_conduct.md
      - Security Policy: governance_and_legal/security.md
