[project]
site_name = "ywbe9tuag740j1x6ezhxvqb7f"
site_url = "https://ywbe9tuag740j1x6ezhxvqb7f.readthedocs.io/en/latest/"
site_description = ""
site_author = "Jevan Goh"

docs_dir = "ot1j9dc4rdqcs45pcvpho3jgr"
language = "en"

repo_url = "https://github.com/jevangoh/ot1j9dc4rdqcs45pcvpho3jgr"
edit_uri = "tree/main/ot1j9dc4rdqcs45pcvpho3jgr/"

extra_css = ["stylesheets/colours.css"]

[project.markdown_extensions.admonition]
[project.markdown_extensions.gfm_admonition]

# --- Theme ---
[project.theme]
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "content.action.view"
]

[project.theme.icon]
repo = "fontawesome/brands/git-alt"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "blue"
accent = "light blue"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# --- Navigation Tree ---
[[nav]]
Home = "index.md"

[[nav]]
Glossary = "glossary.md"

[[nav]]
"User Guide" = [
    "user_guide/index.md",
    { "Pixi (preferred)" = "user_guide/pixi_usage.md" },
    { "Uv" = "user_guide/uv_usage.md" },
    { "Pip" = "user_guide/pip_usage.md" }
]

[[nav]]
"Help and Support" = [
    "help_and_support/index.md",
    { "Ticketing" = "help_and_support/ticketing.md" },
    { "Labels" = "help_and_support/labels.md" }
]

[[nav]]
"Development and Community" = [
    "development_and_community/index.md",
    { "Contributing" = "development_and_community/contributing.md" },
    { "Maintaining" = "development_and_community/maintaining.md" },
    { "Contributors" = "development_and_community/contributors.md" }
]

[[nav]]
"Governance and Legal" = [
    "governance_and_legal/index.md",
    { "Governance" = "governance_and_legal/governance.md" },
    { "Code of Conduct" = "governance_and_legal/code_of_conduct.md" },
    { "Security Policy" = "governance_and_legal/security.md" }
]

# --- Validation ---
[validation.nav]
not_found = "info"
omitted_files = "info"

[validation.links]
not_found = "info"

