[project]
site_name = "ot1j9dc4rdqcs45pcvpho3jgr"
site_url = "https://ot1j9dc4rdqcs45pcvpho3jgr.readthedocs.io/en/latest/"
site_description = ""
site_author = "Jevan Goh"

docs_dir = "ot1j9dc4rdqcs45pcvpho3jgr"

# --- Theme ---
[theme]
features = ["navigation.indexes"]

[[theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# --- Navigation Tree ---
[[nav]]
Home = "index.md"

[[nav]]
Glossary = "glossary.md"

[[nav]]
"User Guide" = [
    "user_guide/index.md",
    { "Pixi (preferred)" = "user_guide/pixi_usage.md" },
    { "Uv" = "user_guide/uv_usage.md" },
    { "Pip" = "user_guide/pip_usage.md" }
]

[[nav]]
"Help and Support" = [
    "help_and_support/index.md",
    { "Ticketing" = "help_and_support/ticketing.md" },
    { "Labels" = "help_and_support/labels.md" }
]

[[nav]]
"Development and Community" = [
    "development_and_community/index.md",
    { "Contributing" = "development_and_community/contributing.md" },
    { "Maintaining" = "development_and_community/maintaining.md" },
    { "Contributors" = "development_and_community/contributors.md" }
]

[[nav]]
"About Repository" = [
    "about_repository/index.md",
    { "Labels" = "about_repository/labels.md" }
]

[[nav]]
"Governance and Legal" = [
    "governance_and_legal/index.md",
    { "Governance" = "governance_and_legal/governance.md" },
    { "Code of Conduct" = "governance_and_legal/code_of_conduct.md" },
    { "Security Policy" = "governance_and_legal/security.md" }
]

# --- Validation ---
[validation.nav]
not_found = "info"
omitted_files = "info"

[validation.links]
not_found = "info"

